const { GoogleSpreadsheet } = require('google-spreadsheet');
const fs = require('fs')
// sweepa-app/api/src/lib/peak-comfort-361602-c2bd1bc6d886.json
// sweepa-app\api\src\lib\peak-comfort-361602-c2bd1bc6d886.json
// we need sheet ID from the

export async function insertEmail(email, Status) {
  const doc = new GoogleSpreadsheet('1MBfmJowTVqVhCyQa1hJByk57xVzaJngEJmpGX1fvAmg');


  console.log("were inside", email)
  console.log("were inside", Status)
  // const creds = require('./peak-comfort-361602-c2bd1bc6d886.json');
  // let creds = fs.readFileSync('peak-comfort-361602-c2bd1bc6d886.json', 'utf-8')
  // console.log("creds",creds)

//  await doc.useServiceAccountAuth(creds);
// Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
await doc.useServiceAccountAuth({
  // env var values are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  type: process.env.TYPE,
  project_id: process.env.PROJECT_ID,
  private_key_id: process.env.PRIVATE_KEY_ID,
  private_key: process.env.PRIVATE_KEY,
  client_email: process.env.CLIENT_EMAIL,
  client_id: process.env.CLIENT_ID,
  auth_uri: process.env.AUTH_URI,
  token_uri: process.env.TOKEN_URI,
  auth_provider_x509_cert_url: process.env.AUTH_PROVIDER_X509_CERT_URL,
  client_x509_cert_url: process.env.CLIENT_X509_CERT_URL
});
await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
console.log(sheet.title);
console.log(sheet.rowCount);
// const sheet.addSheet({ headerValues: ['email', 'Status'] })
const larryRow = await sheet.addRow({  email:  email, Status:Status });
return "Sucess"
}

